export const ADMIN_COPY = {
  'pt-PT': {
    common: {
      loading: 'A carregar…',
      saving: 'A guardar…',
      deleting: 'A eliminar…',
      cancel: 'Cancelar',
      previous: 'Anterior',
      next: 'Seguinte',
      page: 'Página {page} de {total}',
      yes: 'Sim',
      no: 'Não',
      operational: 'Operacional',
      attention: 'Atenção',
      noData: 'Sem dados',
      administrator: 'Administrador',
      user: 'Utilizador',
      active: 'Ativo',
      suspended: 'Suspenso',
      editNamed: 'Editar {name}',
      close: 'Fechar',
      genericError: 'Não foi possível concluir a ação.',
    },
    shell: {
      nav: {
        dashboard: 'Resumo',
        establishments: 'Estabelecimentos',
        commercial: 'Negócios',
        moderation: 'Avaliações',
        users: 'Utilizadores',
        audit: 'Atividade',
        system: 'Sistema',
      },
      places: 'Locais',
      more: 'Mais',
      moreOptions: 'Mais opções',
      adminNavigation: 'Navegação administrativa',
      mobileNavigation: 'Navegação administrativa móvel',
      secondaryNavigation: 'Opções administrativas secundárias',
      closeMore: 'Fechar mais opções',
      backToApp: 'Voltar à app',
      adminRole: 'Administração',
      searchPlaceholder: 'Procurar estabelecimentos, utilizadores, avaliações…',
      searchLabel: 'Procurar no backoffice',
      protected: 'Protegido',
    },
    dashboard: {
      loadError: 'Não foi possível carregar o resumo operacional.',
      quickActionReason: 'Ação rápida a partir do painel',
      loading: 'A preparar o resumo operacional…',
      greeting: 'Bom dia, {name}',
      subtitle: 'Resumo operacional do GlutenFri',
      addEstablishment: 'Adicionar estabelecimento',
      mainMetrics: 'Métricas principais',
      users: 'Utilizadores',
      suspendedCount: '{count} suspensos',
      reviews: 'Avaliações',
      communityActivity: 'Atividade da comunidade',
      establishments: 'Estabelecimentos',
      activeDirectory: 'Diretório ativo',
      pendingReports: 'Denúncias pendentes',
      needReview: 'Precisam de revisão',
      needsAttention: 'Requer atenção',
      noReportedReviews: 'Não há avaliações denunciadas.',
      reason: 'Motivo',
      establishment: 'Estabelecimento',
      author: 'Autor',
      reports: 'Denúncias',
      actions: 'Ações',
      noReason: 'Sem motivo',
      review: 'Rever',
      hiding: 'A ocultar…',
      hide: 'Ocultar',
      viewAllReports: 'Ver todas as denúncias pendentes',
      systemStatus: 'Estado do sistema',
      serverless: 'Serverless a pedido',
      activeMinutes: '{count} min ativa',
      mainCluster: 'Cluster principal',
      placesToRefresh: '{count} registos por atualizar',
      recentActivity: 'Atividade recente',
      noActions: 'Ainda não há ações registadas.',
      deletedAccount: 'Conta eliminada',
      defaultAdmin: 'Administrador',
      targetAt: ' em “{target}”',
      actionsMap: {
        review_hidden: 'ocultou uma avaliação',
        review_restored: 'restaurou uma avaliação',
        user_suspended: 'suspendeu uma conta',
        user_restored: 'restaurou uma conta',
        admin_granted: 'atribuiu uma função de admin',
        admin_revoked: 'removeu uma função de admin',
        establishment_created: 'criou um estabelecimento',
        establishment_updated: 'atualizou um estabelecimento',
        places_refresh_started: 'iniciou a atualização do Google Places',
      },
    },
    establishments: {
      title: 'Estabelecimentos',
      subtitle: 'Gere a qualidade e a segurança do diretório.',
      newEstablishment: 'Novo estabelecimento',
      search: 'Procurar por nome ou morada…',
      allTypes: 'Todos os tipos',
      trustStatus: 'Estado de confiança',
      allRisks: 'Todos os riscos',
      allSources: 'Todas as fontes',
      searching: 'A procurar estabelecimentos…',
      establishment: 'Estabelecimento',
      type: 'Tipo',
      risk: 'Risco',
      source: 'Fonte',
      updated: 'Atualizado',
      edit: 'Editar',
      noAddress: 'Sem morada',
      noResults: 'Não encontrámos resultados com estes filtros.',
      total: '{count} estabelecimentos',
      editEstablishment: 'Editar estabelecimento',
      minimumData: 'Preenche os dados mínimos.',
      auditNotice: 'As alterações ficam registadas.',
      closeEditor: 'Fechar editor',
      name: 'Nome',
      address: 'Morada',
      phone: 'Telefone',
      email: 'Email',
      sourceName: 'Nome da fonte',
      sourceUrl: 'URL HTTPS da fonte',
      lastVerified: 'Última verificação',
      dedicatedKitchen: 'Cozinha dedicada',
      dedicatedMenu: 'Menu dedicado',
      trainedStaff: 'Equipa formada',
      internalNotes: 'Notas internas',
      saveChanges: 'Guardar alterações',
      saved: 'Alterações guardadas',
      saveError: 'Não foi possível guardar as alterações.',
      internalTeam: 'Equipa interna',
      types: {
        restaurant: 'Restaurante',
        store: 'Loja',
        pharmacy: 'Farmácia',
        bakery: 'Pastelaria',
        supermarket: 'Supermercado',
      },
      risks: { none: 'Não avaliado', low: 'Baixo', moderate: 'Moderado', high: 'Alto' },
      trust: {
        CERTIFIED_APC_BIOTRAB: 'Certificado APC/Biotrab',
        COMMUNITY_REPORTED: 'Reportado pela comunidade — não certificado',
        PENDING_VALIDATION: 'Informação pendente de validação',
      },
    },
    moderation: {
      title: 'Moderação de avaliações',
      subtitle: 'Revê provas, motivos e contexto antes de tomar uma decisão.',
      loadError: 'Não foi possível carregar a fila de moderação.',
      decisionError: 'Não foi possível registar a decisão.',
      suspensionError: 'Não foi possível suspender a conta.',
      restoredReason: 'Restaurada através da moderação',
      hiddenReason: 'Ocultada após revisão',
      search: 'Procurar na fila…',
      allReasons: 'Todos os motivos',
      reasons: {
        incorrect_safety: 'Segurança incorreta',
        offensive: 'Conteúdo ofensivo',
        spam: 'Spam',
        personal_data: 'Dados pessoais',
        other: 'Outros',
      },
      allStatuses: 'Todos os estados',
      visiblePlural: 'Visíveis',
      hiddenPlural: 'Ocultas',
      loading: 'A carregar denúncias…',
      emptyQueue: 'A fila está vazia.',
      pendingReport: 'Denúncia pendente',
      reportOne: 'denúncia',
      reportOther: 'denúncias',
      selectReview: 'Seleciona uma avaliação para rever o contexto.',
      hidden: 'Oculta',
      visible: 'Visível',
      noComment: 'A avaliação não contém um comentário escrito.',
      staff: 'Equipa',
      staffLevels: { poor: 'Pouca compreensão', okay: 'Compreensão suficiente', excellent: 'Compreensão excelente' },
      dedicatedMenu: 'Menu dedicado',
      dedicatedKitchen: 'Cozinha dedicada',
      risk: 'Risco',
      submittedReasons: 'Motivos enviados',
      decide: 'Tomar decisão',
      auditNotice: 'Todas as ações ficam registadas com a tua conta, data e motivo.',
      notePlaceholder: 'Nota interna ou justificação da decisão',
      restoreReview: 'Restaurar avaliação',
      hideReview: 'Ocultar avaliação',
      accountSuspended: 'Conta suspensa',
      suspendUser: 'Suspender utilizador',
    },
    users: {
      title: 'Utilizadores',
      subtitle: 'Gere o acesso, a atividade e a segurança das contas.',
      search: 'Procurar por nome ou email…',
      allStatuses: 'Todos os estados',
      activePlural: 'Ativos',
      suspendedPlural: 'Suspensos',
      allRoles: 'Todas as funções',
      administrators: 'Administradores',
      users: 'Utilizadores',
      loading: 'A carregar utilizadores…',
      role: 'Função',
      status: 'Estado',
      reviews: 'Avaliações',
      saved: 'Guardados',
      registered: 'Registo',
      actions: 'Ações',
      noResults: 'Não há utilizadores com estes filtros.',
      visibleAccounts: '{count} contas visíveis',
      closeDetail: 'Fechar detalhe',
      accountData: 'Dados da conta',
      name: 'Nome',
      email: 'Email',
      saveData: 'Guardar dados',
      joined: 'Adesão',
      permissions: 'Permissões',
      permissionsInfo: 'A função administrativa dá acesso completo a este backoffice.',
      removeAdmin: 'Remover função de admin',
      makeAdmin: 'Tornar administrador',
      restoreAccount: 'Restaurar conta',
      suspendAccount: 'Suspender conta',
      currentReason: 'Motivo atual: {reason}',
      notProvided: 'Não indicado',
      accessLoss: 'A pessoa perderá imediatamente o acesso.',
      suspensionReason: 'Motivo obrigatório da suspensão',
      suspendUntil: 'Suspender até (opcional)',
      restoreAccess: 'Restaurar acesso',
      suspendUser: 'Suspender utilizador',
      deleteAccount: 'Eliminar conta',
      deleteWarning: 'Esta ação elimina permanentemente a conta, as avaliações e as relações comerciais. A auditoria administrativa é conservada de forma anonimizada.',
      cannotDeleteSelf: 'Não podes eliminar a conta com a qual tens sessão iniciada.',
      reason: 'Motivo',
      deleteReason: 'Motivo obrigatório da eliminação',
      confirmEmail: 'Escreve {email} para confirmar',
      deleteUser: 'Eliminar utilizador',
      updated: 'Utilizador atualizado.',
      deleted: 'Utilizador eliminado.',
      loadError: 'Não foi possível carregar as contas.',
      updateError: 'Não foi possível atualizar o utilizador.',
      deleteError: 'Não foi possível eliminar o utilizador.',
      roleError: 'Não foi possível atualizar a função.',
      suspensionError: 'Não foi possível atualizar a suspensão.',
    },
    audit: {
      title: 'Atividade administrativa',
      subtitle: 'Registo imutável das decisões realizadas no backoffice.',
      active: 'Auditoria ativa',
      allResources: 'Todos os recursos',
      reviews: 'Avaliações',
      users: 'Utilizadores',
      establishments: 'Estabelecimentos',
      system: 'Sistema',
      loading: 'A ler o histórico…',
      action: 'Ação',
      administrator: 'Administrador',
      resource: 'Recurso',
      reason: 'Motivo',
      date: 'Data',
      deletedAccount: 'Conta eliminada',
      noActions: 'Ainda não há ações registadas.',
      total: '{count} ações',
      actionsMap: {
        review_hidden: 'Avaliação ocultada',
        review_restored: 'Avaliação restaurada',
        user_suspended: 'Utilizador suspenso',
        user_restored: 'Utilizador restaurado',
        admin_granted: 'Permissão de admin concedida',
        admin_revoked: 'Permissão de admin removida',
        establishment_created: 'Estabelecimento criado',
        establishment_updated: 'Estabelecimento atualizado',
        places_refresh_started: 'Atualização do Places iniciada',
      },
    },
    system: {
      loading: 'A verificar serviços…',
      title: 'Estado do sistema',
      subtitle: 'Disponibilidade do backend, Atlas e ciclo de dados do Google Places.',
      refreshStarted: 'Atualização iniciada. Este ecrã será atualizado automaticamente.',
      refreshError: 'Não foi possível iniciar a atualização.',
      serverless: 'Função serverless a pedido',
      activeMinutes: 'Ativa durante {count} minutos',
      mainDatabase: 'Base de dados principal',
      linkedAndStale: '{total} associados · {stale} por atualizar',
      refreshing: 'A atualizar…',
      starting: 'A iniciar…',
      refreshPlaces: 'Atualizar Places',
      cycleTitle: 'Ciclo de atualização do Google Places',
      cycleDescription: 'O workflow semanal atualiza coordenadas com 23 dias de antiguidade, deixando margem antes do limite de 30 dias. Também podes iniciá-lo manualmente aqui.',
      lastRefresh: 'Última atualização',
      processStatus: 'Estado do processo',
      processed: 'Processados',
      errors: 'Erros',
      jobStatuses: { idle: 'Inativo', running: 'Em curso', completed: 'Concluído', failed: 'Falhou' },
    },
    commercial: {
      title: 'Gestão comercial',
      subtitle: 'Pedidos de gestão, permissões e alterações de fichas.',
      claims: 'Pedidos de gestão',
      changes: 'Alterações',
      status: 'Estado',
      all: 'Todos',
      loading: 'A carregar…',
      empty: 'Não há elementos nesta fila.',
      loadError: 'Não foi possível carregar a gestão comercial.',
      actionError: 'Não foi possível concluir a ação.',
      reasonPrompt: 'Motivo para marcar como {status}:',
      actionConfirm: 'Confirmas a ação “{status}” sobre {name}?',
      affectedFields: 'Campos afetados: {fields}',
      changesConfirm: 'Confirmas {action} estas alterações?',
      publish: 'publicar',
      reject: 'rejeitar',
      rejectionReason: 'Motivo da rejeição:',
      approvedReason: 'Revisto e aprovado administrativamente',
      applicant: 'Requerente',
      relationship: 'Relação',
      professionalEmail: 'Email profissional',
      method: 'Método',
      evidence: 'Prova descrita',
      requestInformation: 'Pedir informação',
      approve: 'Aprovar',
      rejectButton: 'Rejeitar',
      revoke: 'Revogar',
      fields: 'Campos',
      current: 'Atual',
      proposed: 'Proposto',
      publishChanges: 'Publicar alterações',
      statuses: {
        pending: 'Pendente',
        needs_information: 'Requer informação',
        approved: 'Aprovada',
        rejected: 'Rejeitada',
        revoked: 'Revogada',
        cancelled: 'Cancelada',
        draft: 'Rascunho',
        pending_review: 'Pendente de revisão',
        published: 'Publicada',
      },
    },
  },
  en: {},
  es: {},
};

ADMIN_COPY.en = {
  common: {
    loading: 'Loading…', saving: 'Saving…', deleting: 'Deleting…', cancel: 'Cancel', previous: 'Previous',
    next: 'Next', page: 'Page {page} of {total}', yes: 'Yes', no: 'No', operational: 'Operational',
    attention: 'Attention', noData: 'No data', administrator: 'Administrator', user: 'User', active: 'Active',
    suspended: 'Suspended', editNamed: 'Edit {name}', close: 'Close', genericError: 'We could not complete the action.',
  },
  shell: {
    nav: { dashboard: 'Overview', establishments: 'Establishments', commercial: 'Businesses', moderation: 'Reviews', users: 'Users', audit: 'Activity', system: 'System' },
    places: 'Places', more: 'More', moreOptions: 'More options', adminNavigation: 'Admin navigation',
    mobileNavigation: 'Mobile admin navigation', secondaryNavigation: 'Secondary admin options',
    closeMore: 'Close more options', backToApp: 'Back to app', adminRole: 'Administrator',
    searchPlaceholder: 'Search establishments, users, reviews…', searchLabel: 'Search the back office', protected: 'Protected',
  },
  dashboard: {
    loadError: 'We could not load the operational overview.', quickActionReason: 'Quick action from the dashboard',
    loading: 'Preparing the operational overview…', greeting: 'Good morning, {name}', subtitle: 'GlutenFri operational overview',
    addEstablishment: 'Add establishment', mainMetrics: 'Main metrics', users: 'Users', suspendedCount: '{count} suspended',
    reviews: 'Reviews', communityActivity: 'Community activity', establishments: 'Establishments', activeDirectory: 'Active directory',
    pendingReports: 'Pending reports', needReview: 'Need review', needsAttention: 'Needs attention',
    noReportedReviews: 'There are no reported reviews.', reason: 'Reason', establishment: 'Establishment', author: 'Author',
    reports: 'Reports', actions: 'Actions', noReason: 'No reason', review: 'Review', hiding: 'Hiding…', hide: 'Hide',
    viewAllReports: 'View all pending reports', systemStatus: 'System status', serverless: 'On-demand serverless',
    activeMinutes: 'Active for {count} min', mainCluster: 'Main cluster', placesToRefresh: '{count} records to refresh',
    recentActivity: 'Recent activity', noActions: 'No actions have been recorded yet.', deletedAccount: 'Deleted account',
    defaultAdmin: 'Administrator', targetAt: ' in “{target}”',
    actionsMap: {
      review_hidden: 'hid a review', review_restored: 'restored a review', user_suspended: 'suspended an account',
      user_restored: 'restored an account', admin_granted: 'granted an admin role', admin_revoked: 'removed an admin role',
      establishment_created: 'created an establishment', establishment_updated: 'updated an establishment',
      places_refresh_started: 'started the Google Places refresh',
    },
  },
  establishments: {
    title: 'Establishments', subtitle: 'Manage the directory’s quality and safety.', newEstablishment: 'New establishment',
    search: 'Search by name or address…', allTypes: 'All types', trustStatus: 'Trust status', allRisks: 'All risk levels',
    allSources: 'All sources', searching: 'Searching establishments…', establishment: 'Establishment', type: 'Type',
    risk: 'Risk', source: 'Source', updated: 'Updated', edit: 'Edit', noAddress: 'No address',
    noResults: 'No results match these filters.', total: '{count} establishments', editEstablishment: 'Edit establishment',
    minimumData: 'Complete the minimum details.', auditNotice: 'Changes are recorded.', closeEditor: 'Close editor',
    name: 'Name', address: 'Address', phone: 'Phone', email: 'Email', sourceName: 'Source name',
    sourceUrl: 'Source HTTPS URL', lastVerified: 'Last verified', dedicatedKitchen: 'Dedicated kitchen',
    dedicatedMenu: 'Dedicated menu', trainedStaff: 'Trained staff', internalNotes: 'Internal notes',
    saveChanges: 'Save changes', saved: 'Changes saved', saveError: 'We could not save the changes.', internalTeam: 'Internal team',
    types: { restaurant: 'Restaurant', store: 'Shop', pharmacy: 'Pharmacy', bakery: 'Bakery', supermarket: 'Supermarket' },
    risks: { none: 'Not assessed', low: 'Low', moderate: 'Moderate', high: 'High' },
    trust: {
      CERTIFIED_APC_BIOTRAB: 'APC/Biotrab certified', COMMUNITY_REPORTED: 'Community reported — not certified',
      PENDING_VALIDATION: 'Information pending validation',
    },
  },
  moderation: {
    title: 'Review moderation', subtitle: 'Review evidence, reasons and context before making a decision.',
    loadError: 'We could not load the moderation queue.', decisionError: 'We could not record the decision.',
    suspensionError: 'We could not suspend the account.', restoredReason: 'Restored from moderation',
    hiddenReason: 'Hidden after review', search: 'Search the queue…', allReasons: 'All reasons',
    reasons: { incorrect_safety: 'Incorrect safety information', offensive: 'Offensive content', spam: 'Spam', personal_data: 'Personal data', other: 'Other' },
    allStatuses: 'All statuses', visiblePlural: 'Visible', hiddenPlural: 'Hidden', loading: 'Loading reports…',
    emptyQueue: 'The queue is empty.', pendingReport: 'Pending report', reportOne: 'report', reportOther: 'reports',
    selectReview: 'Select a review to examine its context.', hidden: 'Hidden', visible: 'Visible',
    noComment: 'The review has no written comment.', staff: 'Staff',
    staffLevels: { poor: 'Limited understanding', okay: 'Adequate understanding', excellent: 'Excellent understanding' },
    dedicatedMenu: 'Dedicated menu',
    dedicatedKitchen: 'Dedicated kitchen', risk: 'Risk', submittedReasons: 'Submitted reasons', decide: 'Make a decision',
    auditNotice: 'Every action is recorded with your account, date and reason.', notePlaceholder: 'Internal note or decision rationale',
    restoreReview: 'Restore review', hideReview: 'Hide review', accountSuspended: 'Account suspended', suspendUser: 'Suspend user',
  },
  users: {
    title: 'Users', subtitle: 'Manage account access, activity and security.', search: 'Search by name or email…',
    allStatuses: 'All statuses', activePlural: 'Active', suspendedPlural: 'Suspended', allRoles: 'All roles',
    administrators: 'Administrators', users: 'Users', loading: 'Loading users…', role: 'Role', status: 'Status',
    reviews: 'Reviews', saved: 'Saved', registered: 'Registered', actions: 'Actions',
    noResults: 'No users match these filters.', visibleAccounts: '{count} visible accounts', closeDetail: 'Close details',
    accountData: 'Account details', name: 'Name', email: 'Email', saveData: 'Save details', joined: 'Joined',
    permissions: 'Permissions', permissionsInfo: 'The administrator role grants full access to this back office.',
    removeAdmin: 'Remove admin role', makeAdmin: 'Make administrator', restoreAccount: 'Restore account',
    suspendAccount: 'Suspend account', currentReason: 'Current reason: {reason}', notProvided: 'Not provided',
    accessLoss: 'The person will immediately lose access.', suspensionReason: 'Required suspension reason',
    suspendUntil: 'Suspend until (optional)', restoreAccess: 'Restore access', suspendUser: 'Suspend user',
    deleteAccount: 'Delete account', deleteWarning: 'This permanently deletes the account, its reviews and business relationships. The administrative audit trail is retained in anonymised form.',
    cannotDeleteSelf: 'You cannot delete the account you are currently signed in with.', reason: 'Reason',
    deleteReason: 'Required deletion reason', confirmEmail: 'Type {email} to confirm', deleteUser: 'Delete user',
    updated: 'User updated.', deleted: 'User deleted.', loadError: 'We could not load the accounts.',
    updateError: 'We could not update the user.', deleteError: 'We could not delete the user.',
    roleError: 'We could not update the role.', suspensionError: 'We could not update the suspension.',
  },
  audit: {
    title: 'Administrative activity', subtitle: 'Immutable record of decisions made in the back office.', active: 'Audit active',
    allResources: 'All resources', reviews: 'Reviews', users: 'Users', establishments: 'Establishments', system: 'System',
    loading: 'Reading history…', action: 'Action', administrator: 'Administrator', resource: 'Resource', reason: 'Reason',
    date: 'Date', deletedAccount: 'Deleted account', noActions: 'No actions have been recorded yet.', total: '{count} actions',
    actionsMap: {
      review_hidden: 'Review hidden', review_restored: 'Review restored', user_suspended: 'User suspended',
      user_restored: 'User restored', admin_granted: 'Admin permission granted', admin_revoked: 'Admin permission removed',
      establishment_created: 'Establishment created', establishment_updated: 'Establishment updated',
      places_refresh_started: 'Places refresh started',
    },
  },
  system: {
    loading: 'Checking services…', title: 'System status', subtitle: 'Backend, Atlas and Google Places data-cycle availability.',
    refreshStarted: 'Refresh started. This screen will update automatically.', refreshError: 'We could not start the refresh.',
    serverless: 'On-demand serverless function', activeMinutes: 'Active for {count} minutes', mainDatabase: 'Main database',
    linkedAndStale: '{total} linked · {stale} to refresh', refreshing: 'Refreshing…', starting: 'Starting…',
    refreshPlaces: 'Refresh Places', cycleTitle: 'Google Places refresh cycle',
    cycleDescription: 'The weekly workflow refreshes coordinates that are 23 days old, leaving a margin before the 30-day limit. You can also start it manually here.',
    lastRefresh: 'Last refresh', processStatus: 'Process status', processed: 'Processed', errors: 'Errors',
    jobStatuses: { idle: 'Idle', running: 'Running', completed: 'Completed', failed: 'Failed' },
  },
  commercial: {
    title: 'Business management', subtitle: 'Claims, permissions and listing changes.', claims: 'Claims', changes: 'Changes',
    status: 'Status', all: 'All', loading: 'Loading…', empty: 'There are no items in this queue.',
    loadError: 'We could not load business management.', actionError: 'We could not complete the action.',
    reasonPrompt: 'Reason for marking as {status}:', actionConfirm: 'Confirm “{status}” for {name}?',
    affectedFields: 'Affected fields: {fields}', changesConfirm: 'Confirm you want to {action} these changes?',
    publish: 'publish', reject: 'reject', rejectionReason: 'Reason for rejection:', approvedReason: 'Administratively reviewed and approved',
    applicant: 'Applicant', relationship: 'Relationship', professionalEmail: 'Business email', method: 'Method',
    evidence: 'Evidence provided', requestInformation: 'Request information', approve: 'Approve',
    rejectButton: 'Reject', revoke: 'Revoke', fields: 'Fields', current: 'Current', proposed: 'Proposed',
    publishChanges: 'Publish changes',
    statuses: { pending: 'Pending', needs_information: 'Needs information', approved: 'Approved', rejected: 'Rejected', revoked: 'Revoked', cancelled: 'Cancelled', draft: 'Draft', pending_review: 'Pending review', published: 'Published' },
  },
};

ADMIN_COPY.es = {
  common: {
    loading: 'Cargando…', saving: 'Guardando…', deleting: 'Eliminando…', cancel: 'Cancelar', previous: 'Anterior',
    next: 'Siguiente', page: 'Página {page} de {total}', yes: 'Sí', no: 'No', operational: 'Operativo',
    attention: 'Atención', noData: 'Sin datos', administrator: 'Administrador', user: 'Usuario', active: 'Activo',
    suspended: 'Suspendido', editNamed: 'Editar {name}', close: 'Cerrar', genericError: 'No pudimos completar la acción.',
  },
  shell: {
    nav: { dashboard: 'Resumen', establishments: 'Establecimientos', commercial: 'Negocios', moderation: 'Reseñas', users: 'Usuarios', audit: 'Actividad', system: 'Sistema' },
    places: 'Lugares', more: 'Más', moreOptions: 'Más opciones', adminNavigation: 'Navegación administrativa',
    mobileNavigation: 'Navegación administrativa móvil', secondaryNavigation: 'Opciones administrativas secundarias',
    closeMore: 'Cerrar más opciones', backToApp: 'Volver a la app', adminRole: 'Administración',
    searchPlaceholder: 'Buscar establecimientos, usuarios, reseñas…', searchLabel: 'Buscar en el backoffice', protected: 'Protegido',
  },
  dashboard: {
    loadError: 'No pudimos cargar el resumen operativo.', quickActionReason: 'Acción rápida desde el panel',
    loading: 'Preparando el resumen operativo…', greeting: 'Buenos días, {name}', subtitle: 'Resumen operativo de GlutenFri',
    addEstablishment: 'Añadir establecimiento', mainMetrics: 'Métricas principales', users: 'Usuarios', suspendedCount: '{count} suspendidos',
    reviews: 'Reseñas', communityActivity: 'Actividad de la comunidad', establishments: 'Establecimientos', activeDirectory: 'Directorio activo',
    pendingReports: 'Reportes pendientes', needReview: 'Necesitan revisión', needsAttention: 'Necesita atención',
    noReportedReviews: 'No hay reseñas reportadas.', reason: 'Motivo', establishment: 'Establecimiento', author: 'Autor',
    reports: 'Reportes', actions: 'Acciones', noReason: 'Sin motivo', review: 'Revisar', hiding: 'Ocultando…', hide: 'Ocultar',
    viewAllReports: 'Ver todos los reportes pendientes', systemStatus: 'Estado del sistema', serverless: 'Serverless bajo demanda',
    activeMinutes: '{count} min activa', mainCluster: 'Cluster principal', placesToRefresh: '{count} registros por refrescar',
    recentActivity: 'Actividad reciente', noActions: 'Todavía no hay acciones registradas.', deletedAccount: 'Cuenta eliminada',
    defaultAdmin: 'Administrador', targetAt: ' en “{target}”',
    actionsMap: {
      review_hidden: 'ocultó una reseña', review_restored: 'restauró una reseña', user_suspended: 'suspendió una cuenta',
      user_restored: 'restauró una cuenta', admin_granted: 'asignó un rol de admin', admin_revoked: 'retiró un rol de admin',
      establishment_created: 'creó un establecimiento', establishment_updated: 'actualizó un establecimiento',
      places_refresh_started: 'inició el refresco de Google Places',
    },
  },
  establishments: {
    title: 'Establecimientos', subtitle: 'Gestiona la calidad y seguridad del directorio.', newEstablishment: 'Nuevo establecimiento',
    search: 'Buscar por nombre o dirección…', allTypes: 'Todos los tipos', trustStatus: 'Estado de confianza', allRisks: 'Todos los riesgos',
    allSources: 'Todas las fuentes', searching: 'Buscando establecimientos…', establishment: 'Establecimiento', type: 'Tipo',
    risk: 'Riesgo', source: 'Fuente', updated: 'Actualizado', edit: 'Editar', noAddress: 'Sin dirección',
    noResults: 'No encontramos resultados con esos filtros.', total: '{count} establecimientos', editEstablishment: 'Editar establecimiento',
    minimumData: 'Completa los datos mínimos.', auditNotice: 'Los cambios quedan registrados.', closeEditor: 'Cerrar editor',
    name: 'Nombre', address: 'Dirección', phone: 'Teléfono', email: 'Email', sourceName: 'Nombre de la fuente',
    sourceUrl: 'URL HTTPS de la fuente', lastVerified: 'Última verificación', dedicatedKitchen: 'Cocina dedicada',
    dedicatedMenu: 'Menú dedicado', trainedStaff: 'Personal capacitado', internalNotes: 'Notas internas',
    saveChanges: 'Guardar cambios', saved: 'Cambios guardados', saveError: 'No pudimos guardar los cambios.', internalTeam: 'Equipo interno',
    types: { restaurant: 'Restaurante', store: 'Tienda', pharmacy: 'Farmacia', bakery: 'Pastelería', supermarket: 'Supermercado' },
    risks: { none: 'Sin evaluar', low: 'Bajo', moderate: 'Moderado', high: 'Alto' },
    trust: {
      CERTIFIED_APC_BIOTRAB: 'Certificado APC/Biotrab', COMMUNITY_REPORTED: 'Reportado por la comunidad — no certificado',
      PENDING_VALIDATION: 'Información pendiente de validación',
    },
  },
  moderation: {
    title: 'Moderación de reseñas', subtitle: 'Revisa evidencia, motivos y contexto antes de tomar una decisión.',
    loadError: 'No pudimos cargar la cola de moderación.', decisionError: 'No pudimos registrar la decisión.',
    suspensionError: 'No pudimos suspender la cuenta.', restoredReason: 'Restaurada desde moderación',
    hiddenReason: 'Ocultada tras revisión', search: 'Buscar en la cola…', allReasons: 'Todos los motivos',
    reasons: { incorrect_safety: 'Seguridad incorrecta', offensive: 'Contenido ofensivo', spam: 'Spam', personal_data: 'Datos personales', other: 'Otros' },
    allStatuses: 'Todos los estados', visiblePlural: 'Visibles', hiddenPlural: 'Ocultas', loading: 'Cargando reportes…',
    emptyQueue: 'La cola está vacía.', pendingReport: 'Reporte pendiente', reportOne: 'reporte', reportOther: 'reportes',
    selectReview: 'Selecciona una reseña para revisar su contexto.', hidden: 'Oculta', visible: 'Visible',
    noComment: 'La reseña no contiene comentario escrito.', staff: 'Personal',
    staffLevels: { poor: 'Comprensión limitada', okay: 'Comprensión suficiente', excellent: 'Comprensión excelente' },
    dedicatedMenu: 'Menú dedicado',
    dedicatedKitchen: 'Cocina dedicada', risk: 'Riesgo', submittedReasons: 'Motivos enviados', decide: 'Tomar decisión',
    auditNotice: 'Toda acción quedará registrada con tu cuenta, fecha y motivo.', notePlaceholder: 'Nota interna o justificación de la decisión',
    restoreReview: 'Restaurar reseña', hideReview: 'Ocultar reseña', accountSuspended: 'Cuenta suspendida', suspendUser: 'Suspender usuario',
  },
  users: {
    title: 'Usuarios', subtitle: 'Gestiona acceso, actividad y seguridad de las cuentas.', search: 'Buscar por nombre o email…',
    allStatuses: 'Todos los estados', activePlural: 'Activos', suspendedPlural: 'Suspendidos', allRoles: 'Todos los roles',
    administrators: 'Administradores', users: 'Usuarios', loading: 'Cargando usuarios…', role: 'Rol', status: 'Estado',
    reviews: 'Reseñas', saved: 'Guardados', registered: 'Registro', actions: 'Acciones',
    noResults: 'No hay usuarios con esos filtros.', visibleAccounts: '{count} cuentas visibles', closeDetail: 'Cerrar detalle',
    accountData: 'Datos de la cuenta', name: 'Nombre', email: 'Email', saveData: 'Guardar datos', joined: 'Alta',
    permissions: 'Permisos', permissionsInfo: 'El rol administrativo da acceso completo a este backoffice.',
    removeAdmin: 'Quitar rol de admin', makeAdmin: 'Hacer administrador', restoreAccount: 'Restaurar cuenta',
    suspendAccount: 'Suspender cuenta', currentReason: 'Motivo actual: {reason}', notProvided: 'No indicado',
    accessLoss: 'La persona perderá acceso inmediatamente.', suspensionReason: 'Motivo obligatorio de la suspensión',
    suspendUntil: 'Suspender hasta (opcional)', restoreAccess: 'Restaurar acceso', suspendUser: 'Suspender usuario',
    deleteAccount: 'Eliminar cuenta', deleteWarning: 'Esta acción elimina permanentemente la cuenta, sus reseñas y sus relaciones comerciales. La auditoría administrativa se conserva anonimizada.',
    cannotDeleteSelf: 'No puedes eliminar la cuenta con la que has iniciado sesión.', reason: 'Motivo',
    deleteReason: 'Motivo obligatorio de la eliminación', confirmEmail: 'Escribe {email} para confirmar', deleteUser: 'Eliminar usuario',
    updated: 'Usuario actualizado.', deleted: 'Usuario eliminado.', loadError: 'No pudimos cargar las cuentas.',
    updateError: 'No pudimos actualizar el usuario.', deleteError: 'No pudimos eliminar el usuario.',
    roleError: 'No pudimos actualizar el rol.', suspensionError: 'No pudimos actualizar la suspensión.',
  },
  audit: {
    title: 'Actividad administrativa', subtitle: 'Registro inmutable de las decisiones realizadas desde el backoffice.', active: 'Auditoría activa',
    allResources: 'Todos los recursos', reviews: 'Reseñas', users: 'Usuarios', establishments: 'Establecimientos', system: 'Sistema',
    loading: 'Leyendo el historial…', action: 'Acción', administrator: 'Administrador', resource: 'Recurso', reason: 'Motivo',
    date: 'Fecha', deletedAccount: 'Cuenta eliminada', noActions: 'Todavía no hay acciones registradas.', total: '{count} acciones',
    actionsMap: {
      review_hidden: 'Reseña ocultada', review_restored: 'Reseña restaurada', user_suspended: 'Usuario suspendido',
      user_restored: 'Usuario restaurado', admin_granted: 'Permiso de admin concedido', admin_revoked: 'Permiso de admin retirado',
      establishment_created: 'Establecimiento creado', establishment_updated: 'Establecimiento actualizado',
      places_refresh_started: 'Refresco de Places iniciado',
    },
  },
  system: {
    loading: 'Comprobando servicios…', title: 'Estado del sistema', subtitle: 'Disponibilidad del backend, Atlas y ciclo de datos de Google Places.',
    refreshStarted: 'Refresco iniciado. Esta pantalla se actualizará automáticamente.', refreshError: 'No pudimos iniciar el refresco.',
    serverless: 'Función serverless bajo demanda', activeMinutes: 'Activa durante {count} minutos', mainDatabase: 'Base principal',
    linkedAndStale: '{total} vinculados · {stale} por refrescar', refreshing: 'Refrescando…', starting: 'Iniciando…',
    refreshPlaces: 'Refrescar Places', cycleTitle: 'Ciclo de refresco de Google Places',
    cycleDescription: 'El workflow semanal actualiza coordenadas con 23 días de antigüedad, dejando margen antes del límite de 30 días. También puedes iniciarlo manualmente desde aquí.',
    lastRefresh: 'Último refresco', processStatus: 'Estado del proceso', processed: 'Procesados', errors: 'Errores',
    jobStatuses: { idle: 'Inactivo', running: 'En curso', completed: 'Completado', failed: 'Fallido' },
  },
  commercial: {
    title: 'Gestión comercial', subtitle: 'Reclamaciones, permisos y cambios de fichas.', claims: 'Reclamaciones', changes: 'Cambios',
    status: 'Estado', all: 'Todos', loading: 'Cargando…', empty: 'No hay elementos en esta cola.',
    loadError: 'No se pudo cargar la gestión comercial.', actionError: 'No se pudo completar la acción.',
    reasonPrompt: 'Motivo para marcar como {status}:', actionConfirm: '¿Confirmas la acción “{status}” sobre {name}?',
    affectedFields: 'Campos afectados: {fields}', changesConfirm: '¿Confirmas {action} estos cambios?',
    publish: 'publicar', reject: 'rechazar', rejectionReason: 'Motivo del rechazo:', approvedReason: 'Revisado y aprobado administrativamente',
    applicant: 'Solicitante', relationship: 'Relación', professionalEmail: 'Email profesional', method: 'Método',
    evidence: 'Evidencia descrita', requestInformation: 'Pedir información', approve: 'Aprobar',
    rejectButton: 'Rechazar', revoke: 'Revocar', fields: 'Campos', current: 'Actual', proposed: 'Propuesto',
    publishChanges: 'Publicar cambios',
    statuses: { pending: 'Pendiente', needs_information: 'Necesita información', approved: 'Aprobada', rejected: 'Rechazada', revoked: 'Revocada', cancelled: 'Cancelada', draft: 'Borrador', pending_review: 'Pendiente de revisión', published: 'Publicada' },
  },
};

export function formatAdminCopy(template, variables = {}) {
  return String(template).replace(/\{(\w+)\}/g, (_, key) => variables[key] ?? `{${key}}`);
}
